I appear to have forgotten how to write conditionals in rules files.
I have relearned this, and fixed another couple of minor idiocies I had
committed in the interim. The result now appears to properly find the
generated egg in Ubuntu and if it can't find the egg has a sensible exit
clause.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -70,10 +70,12 @@ install-prereq:
 install-python%:
 # Force setuptools, but reset sys.argv[0] to 'setup.py' because setup.py files expect that.
 	cd diamond;python$* -c "import setuptools,sys;f='setup.py';sys.argv[0]=f;execfile(f,{'__file__':f,'__name__':'__main__'})" install --prefix=/usr --no-compile --single-version-externally-managed		 --root $(CURDIR)/debian/${PACKAGE_NAME}
-	if [ -f debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-${DEB_UPSTREAM_VERSION}.egg-info ]; then
-	    mv debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-${DEB_UPSTREAM_VERSION}.egg-info		 debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}.egg-info
-	elif [ -f debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-py${PYVERS}-${DEB_UPSTREAM_VERSION}.egg-info ]; then
-	    mv debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-py${PYVERS}-${DEB_UPSTREAM_VERSION}.egg-info		 debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}.egg-info
+	if [ -d debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-${DEB_UPSTREAM_VERSION}.egg-info ]; then \
+	    mv debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-${DEB_UPSTREAM_VERSION}.egg-info		 debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}.egg-info ; \
+	elif [ -d debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-${DEB_UPSTREAM_VERSION}-py$*.egg-info ]; then \
+	    mv debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}-${DEB_UPSTREAM_VERSION}-py$*.egg-info		 debian/${PACKAGE_NAME}/usr/lib/python$*/site-packages/${MODULE_NAME}.egg-info ; \
+	else \
+	    echo "Failed to locate python egg, was it built correctly?" && exit 1 ; \
 	fi
 
 binary-arch: build-libspud install-libspud install-spudtools
